# 多账号多区域EC2部署配置示例
accounts:
  - account_id: "111111111111"
    regions:
      - region: "ap-northeast-1"
        subnets:
          - subnet_id: "subnet-xxxxxx1"
            instance_count: 1
          - subnet_id: "subnet-xxxxxx2"
            instance_count: 2
      - region: "us-west-2"
        subnets:
          - subnet_id: "subnet-yyyyyy1"
            instance_count: 1
  - account_id: "222222222222"
    regions:
      - region: "eu-central-1"
        subnets:
          - subnet_id: "subnet-zzzzzz1"
            instance_count: 1
